### ISSUE TITLE
The new version is still now downloading from freetutorials.ca.

### ISSUE THREAD

**Issue by dw-liedji** [TimilsinaBimal/freetutorials-dl#2]
The new version is still now downloading from freetutorials.ca.

Please test this following link.

 https://www.freetutorials.ca/video/mastering-react/10/0

This is the error traceback:

$ fts-dl --url  https://www.freetutorials.ca/video/mastering-react/10/0

Traceback (most recent call last):
  File "/home/liedji/anaconda3/bin/fts-dl", line 8, in <module>
    sys.exit(fts())
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/freetutorials_dl/cli.py", line 13, in fts
    course = Course(url)
  File "/home/liedji/anaconda3/lib/python3.8/site-packages/freetutorials_dl/course.py", line 20, in __init__
    self.course_title = soup.select_one(
AttributeError: 'NoneType' object has no attribute 'text'

Please test the above link when trying to solve this issue. 

Thank you and waiting for a solution.

**Comment by TimilsinaBimal** [comment]
First of all, Thank you for the issue! I was able to reproduce the issue from the mentioned URL. 
But, for now, the script doesn't support a single video downloading feature. This script only downloads complete course. And I am working on a single video downloading feature. It will be available soon!
**If you like to work on that! Please mention me! I will assign you the task.**
And one more, Some videos are not working on the website itself due to their server issue, try to play at least 2-3 videos to be assured that the problem is not from the server but from the script.
Thank you!

**Comment by dw-liedji** [comment]
Hello again @TimilsinaBimal .

I have refactor the code and classes to support  single, section and full course downloading. However, it's just working for videos  from ```https://www.learningcrux.com/```. It's not able to download any videos from ```freetutorials.ca``` ; not even the full course url. It is just creation folder but nothing is found inside.  **I would like to contribute but don't how to process to add the refactory code**. If you look at my previous message, you'll see that at the end of the traceback, we have this error message ```self.course_title = soup.select_one(
AttributeError: 'NoneType' object has no attribute 'text'``` . I have fixed that, the main issue, it's actually on downloading from ```freetutorials.ca```

Thank you.

**Comment by TimilsinaBimal** [comment]
#### Hey @l-i-e-d-j-i-6-7-8-w-d  Here is How you can contribute
1. Fork this repo and clone forked repo to your machine.
2. Make necessary changes and push to your repo.
3. Create a pull request, Please make a new branch if possible while creating a pull request.

Will review the code and merge it if it doesn't conflict with any of our present code!

**Comment by dw-liedji** [comment]
What about the downloading from freetutorials.ca ?

**Comment by TimilsinaBimal** [comment]
I will make the necessary changes! You can create a pull request for now.
